[security] feature add or-option
swaggo/swag pull request #1151
Opened 2022-02-28 15:24 UTC by Lehp

**Describe the PR**
Feature to generate OR-security option for swagger files.

**Relation issue**
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1149)

**Additional context**
Sorry for not waiting for any approval Was watching at the source code and almost accidentally coded this.

I desperately need this function to make this repo useful for my company.

2022-03-03 18:55 UTC, ubogdan commented
Please fix the unit tests to go forward with a code review.

2022-03-04 15:31 UTC, Lehp commented
> Please fix the unit tests to go forward with a code review.

Hey ubogdan thx for your res. 
I must admit I just learned how to code in GO a month ago. So i am very confused with this library. 
Somehow the tests concerning my change worked. I had a permission denied error in TestWithMonkeyFilepathAbs test. I believe it to be a local Problem but don't know what it means and it's quite hard for me to debug this code. Build is green after run fmt commit but I'm suspicious. Is everythink ok or where and what is the problem rn?

2022-03-05 17:49 UTC, ubogdan requested changes
See comments.

2022-03-05 17:49 UTC, ubogdan commented on operation.go
> +func (operation *Operation) ProcessSecurityOption(securityOption string, securityMap SecurityMap) {
We don't need additional export. Even make this a private function even move the code inside the for loop.

2022-03-05 17:49 UTC, ubogdan commented on operation.go
> +type SecurityMap map[string][]string
Useless definition. Please remove.

2022-03-07 13:28 UTC, ubogdan commented
unit tests are failing...

2022-03-08 09:56 UTC, Lehp commented
I'm having file-permission errors running tests locally. Is it a git convention that tests on the repo only run when someone approves the workflow?

2022-03-08 10:06 UTC, ubogdan commented
@Lehp Workflow approval is required because you are firs time contributor on this repo.

2022-03-08 10:09 UTC, Lehp commented
@ubogdan do you know why this tests fails locally for me? 
gomonkey.ApplyFunc panics for me and I don't know why.
![image](https://user-images.githubusercontent.com/40690143/157214915-15caf3fd-c49e-41df-b059-36fce2bc4d94.png)

2022-03-08 11:06 UTC, ubogdan commented
See [notes](https://github.com/agiledragon/gomonkey#notes) : 
`A panic may happen when a goroutine is patching a function or a member method that is visited by another goroutine at the same time. That is to say, gomonkey is not threadsafe.`

2022-03-08 11:07 UTC, ubogdan approved these changes
LGTM

2022-03-08 11:07 UTC, merged

2022-03-08 11:09 UTC, ubogdan commented
I just realized the README.nd wasn't updated so the users can benefit from this feature. Can you please create another PR with the documentation update ?.