Generics support
swaggo/swag pull request #1277
Opened 2022-07-31 21:44 UTC by FabianMartin

**Describe the PR**
Extends the generic support for go 1.8

1. Adds support for nested generics (generic[string, generic[int]])
2. Adds support for array parameter on generics (generic[string, []string])
3. Adds support for generic properties on structs
4. Adds support for built-in types in generics

**Relation issue**
https://github.com/swaggo/swag/issues/1170
https://github.com/swaggo/swag/issues/1213

**Additional context**
All changes are backward compatible and have been tested with Go 1.15, 1.16, 1.17 and 1.18.4. It is possible that other issues, besides the ones mentioned, have been fixed.

2022-08-01 17:00 UTC, ubogdan requested changes
Good job so far. Please update according to the comments.

2022-08-01 17:00 UTC, ubogdan commented on generics.go
Else if is hard to follow, please rewrite it with a `switch case` statement for better readability.

```go
	switch astExpr := expr.(type) {
	case *ast.Ident:
		//TODO fill the code here
	case *ast.ArrayType:
		return &ast.ArrayType{
			Elt:    resolveType(astExpr.Elt, field, genericParamTypeDefs),
			Len:    astExpr.Len,
			Lbrack: astExpr.Lbrack,
		}
	}
```

2022-08-01 17:00 UTC, ubogdan commented on generics.go
> +				genericParam = genericParam[2:]
isArray is used only once. Please put the excretion inside if statement

```go
if ! (len(genericParam) > 2 && genericParam[:2] == "[]") {
 break 
}
genericParam = genericParam[2:]
arrayDepth++
```

2022-08-01 17:00 UTC, ubogdan commented on generics.go
> +				Name:       genericParam,
Don't need to initialize TypeSpec since is nill by default.

2022-08-01 22:07 UTC, FabianMartin commented
Hi @ubogdan,
thanks for the feedback. I have made the suggested changes and added new tests.

2022-08-02 09:01 UTC, ubogdan approved these changes
LGTM

2022-08-02 09:02 UTC, merged

2022-08-02 09:02 UTC, ubogdan commented
@FabianMartin Thanks for your contribution.

2022-08-04 19:07 UTC, johan-lejdung commented
Fantastic, much appreciated @FabianMartin ! Looking forward to this getting released so that I can try it with my generic structs that's currently not being picked up correctly 🙏 @ubogdan do you have any publicly available release schedule?

With any luck this might also solve https://github.com/swaggo/swag/issues/1253

2022-08-06 14:12 UTC, FabianMartin commented
@johan-lejdung Thank you for your feedback. A fix for your issue is included in PR https://github.com/swaggo/swag/pull/1281.