Add check for nil otherTypeDef
swaggo/swag pull request #1372
Opened 2022-10-29 05:50 UTC by farexw

**Relation issue**
[e.g. https://github.com/swaggo/swag/pull/118/files](https://github.com/swaggo/swag/issues/1368)

2022-10-29 05:53 UTC, farexw commented
This PR solve the problem [issue](https://github.com/swaggo/swag/issues/1368)

2022-10-29 15:02 UTC, sdghchj commented
Sorry,  I introduced this bug.

2022-10-29 15:14 UTC, sdghchj requested changes

2022-10-29 15:14 UTC, sdghchj commented on packages.go
> +					if ok && anotherTypeDef != nil {
As follows:

```
if ok {
        if( anotherTypeDef == nil ){
                typeSpecDef.NotUnique = true
		pkgDefs.uniqueDefinitions[typeSpecDef.TypeName()] = typeSpecDef
        }else  if typeSpecDef.PkgPath != anotherTypeDef.PkgPath {
		anotherTypeDef.NotUnique = true
		typeSpecDef.NotUnique = true
		pkgDefs.uniqueDefinitions[fullName] = nil
		pkgDefs.uniqueDefinitions[anotherTypeDef.TypeName()] = anotherTypeDef
		pkgDefs.uniqueDefinitions[typeSpecDef.TypeName()] = typeSpecDef
	}
} else {
        pkgDefs.uniqueDefinitions[fullName] = typeSpecDef
}
```

2022-10-29 15:14 UTC, sdghchj commented on packages.go
> +					if ok && anotherTypeDef != nil {
and also modify the function `parseFunctionScopedTypesFromFile`

2022-10-29 16:11 UTC, farexw commented on packages.go
> +					if ok && anotherTypeDef != nil {
Oк, I understand

2022-10-29 16:12 UTC, farexw commented on packages.go
> +					if ok && anotherTypeDef != nil {
> and also modify the function `parseFunctionScopedTypesFromFile`

Oк, I understand

2022-10-29 16:14 UTC, farexw reviewed
ok

2022-10-30 06:54 UTC, farexw commented on packages.go
> +					if ok && anotherTypeDef != nil {
Done, tank you for your attention

2022-10-30 10:24 UTC, sdghchj requested changes

2022-10-30 10:24 UTC, sdghchj commented on packages.go
> +						if anotherTypeDef != nil {
here the condition is ==

```
if anotherTypeDef == nil {

}
```

2022-10-30 10:24 UTC, sdghchj commented on packages.go
> +									if anotherTypeDef != nil {
the same as above

2022-10-30 10:51 UTC, farexw commented on packages.go
> +						if anotherTypeDef != nil {
fixed

2022-10-30 10:51 UTC, farexw commented on packages.go
> +									if anotherTypeDef != nil {
fidxed

2022-10-30 11:17 UTC, sdghchj approved these changes
LGTM.
Thank you!

2022-10-30 11:35 UTC, merged