update modules
swaggo/swag pull request #1715
Opened 2023-12-11 09:33 UTC by jvilhuber

**Describe the PR**

Update modules (go get -u ./...; go mod tidy; make) to make security scanners happy.

**Relation issue**

**Additional context**

2023-12-18 06:17 UTC, sdghchj commented
strings.Cut from higher go version failed in go v.17.   
@ubogdan  Give up this upgrade or give up go v1.17?

2023-12-18 06:21 UTC, ubogdan commented
Yes , please upgate the gha and Readme . remove 1.17 and as 1.21

2023-12-18 08:25 UTC, sdghchj commented
@jvilhuber Hello, rebase your branch on the latest master, please.

2023-12-18 10:25 UTC, jvilhuber commented
pulled in latest changes and ran `go get -u ./...; go mod tidy` one more time (to pick up any changes due to upgrade from go 1.17 to go 1.18 in the base).

2024-01-02 01:16 UTC, sdghchj commented
@jvilhuber Sorry, my fault to bother you to rebase again.

2024-01-08 01:27 UTC, sdghchj approved these changes

2024-01-08 01:35 UTC, sdghchj requested changes
package `github.com/go-openapi/spec@v0.20.13` needs go1.19 at least, not compatibale with go1.18

2024-02-14 17:07 UTC, closed without merging