Feat: allow enum ordered const name override
swaggo/swag pull request #1779
Opened 2024-03-28 15:28 UTC by drewsilcock

**Describe the PR**
Add ability to override name of enum variant generated from ordered constant using `// @name VariantName` in the same way you can do for types.

**Relation issue**
https://github.com/swaggo/swag/issues/1778

**Additional context**
N/A

2024-04-21 20:25 UTC, ubogdan requested changes

2024-04-21 20:25 UTC, ubogdan commented on const.go
> +	} else if overriddenName := nameOverride(cv.Comment); overriddenName != "" {
prease remove the useless else for better reading

2024-04-21 20:25 UTC, ubogdan commented on types.go
> +	} else if overriddenName := nameOverride(t.TypeSpec.Comment); overriddenName != "" {
same here

2024-04-21 20:26 UTC, ubogdan commented
@drewsilcock Please rebase and update the code.

2024-04-29 10:56 UTC, drewsilcock commented
Thanks for taking the time to take a look at this @ubogdan - I've rebased and updated based on the linter and your comments.

2024-07-04 10:02 UTC, drewsilcock commented
@ubogdan @sdghchj Any chance of a re-review / merge? Would be great to get this in. Thanks in advance 🙂

2024-07-05 02:20 UTC, sdghchj commented
I can't see the passed checks of all the tests. 
I am afraid I will be noticed again the test failure if I merge this PR.

2024-07-05 12:40 UTC, drewsilcock commented
> I can't see the passed checks of all the tests. I am afraid I will be noticed again the test failure if I merge this PR.

Is there something additional we need to do for the full test suite to run on this PR? (The tests pass just fine when I run it locally on Go v1.22.)

2024-07-06 02:13 UTC, sdghchj approved these changes

2024-07-06 02:17 UTC, sdghchj commented
@ubogdan was requested to review。
long time no see him.

2024-07-10 09:42 UTC, drewsilcock commented
Thanks for approving, I re-requested a review from @ubogdan after making the changes he requested, is his approval required for merging? GitHub seems to be blocking merge until the review request is approved or dismissed.

2025-02-25 16:36 UTC, reecerussell commented
This would be super helpful, is there any update on this?

2025-06-16 09:25 UTC, drewsilcock commented
> This would be super helpful, is there any update on this?

This PR is currently blocked as @ubogdan requested changes and isn't around to approve the changes once I made them (I'm not sure whether he's still involved in this project or not). Best solution might be for me to re-submit this PR (after merging in any recent changes as GitHub tells me I need to do) so that it is no longer blocked by requiring ubogdan's re-approval – I will aim to get this done within the next couple of weeks and will then close this PR in favour of the new one.

2025-07-23 11:16 UTC, drewsilcock commented
I've now submitted another PR, #2046, which has this functionality in plus some test improvements and a related bug fix. As such, I'm closing this PR in favour of the other one, which isn't blocked by requiring re-approval from ubogdan.

2025-07-23 11:16 UTC, closed without merging